# 50 Functions of Numpy

In [3]:
import numpy as np

In [15]:
#1 creating a array with arange numpy function its similar to range python function
a=np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [16]:
#2 First creating and then reshaping an array
b=np.arange(14).reshape(2,7)# Here we reshaping with 2 rows and 7 columns
print(b)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]


In [23]:
#We can also change a big array in a multi dimension, Like
ar=np.arange(24).reshape(4,3,2)# 4 sides 3 rows and 2 columns
print(ar)


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [30]:
#3 Creating an array
np.array([[2,3],[3,2]])

array([[2, 3],
       [3, 2]])

In [34]:
my_array=np.array([1,2,3,4,5,6,7,7,8])
print(my_array)

[1 2 3 4 5 6 7 7 8]


In [36]:
#4 checking type
type(my_array)

numpy.ndarray

In [39]:
#5 How we check the data type in a array
a.dtype
my_array.dtype

dtype('int32')

In [41]:
#6 checking size of array
my_array.size

9

In [50]:
#7 Check dimention of an array
print(my_array.ndim)
ar.ndim

3

In [44]:
#8 Shape function
my_array.shape

(9,)

In [49]:
print(a.shape)
ar.shape# this matrix is given above

(20,)


(4, 3, 2)

In [54]:
#9 Set minimum dimention of the array
us=np.array([0,1,2,3,4,5,6],ndmin=4)
us

array([[[[0, 1, 2, 3, 4, 5, 6]]]])

In [56]:
#10 set data type of the array
usman=np.array([1,2,3,4,5,6],dtype=float)
usman

array([1., 2., 3., 4., 5., 6.])

In [65]:
#11 checking the size of the items in bytes its float thats it showing 8 bytes
b=np.array([2.1,3.3,5.6])
print(b.itemsize)
B=np.array([1,2,3,4,4])
B.itemsize # Will show 4

8


4

In [75]:
#12 change the value in the array
B[4]=45
print(B)

[ 1  2  3  4 45]


In [84]:
#13 Slicing
neww=B[1:5]
print(neww)

[ 2  3  4 45]


In [87]:
#14 Assigning new values while slicing
B[1:5]=2,2,2,2
print(B)

[1 2 2 2 2]


In [89]:
#15
bool_arr=np.array([1,.5,0,'aa',''],dtype=bool)
print(bool_arr)

[ True  True False  True False]


In [93]:
#16
my=[1,2,3,4]
print(np.sum(my))#Numpy function

10


In [97]:
#17
n=np.array([12,34,56,78])
n.min()

12

In [100]:
#18
n.max()

78

In [113]:
#19
np.sqrt(my)

array([1.        , 1.41421356, 1.73205081, 2.        ])

# A Multidimensional Array Object

In [115]:
#20
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [117]:
#21
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [119]:
#22
np.empty([1,3]) #it will pick the garbage any data

array([[2.1, 3.3, 5.6]])

In [128]:
#23
arr=np.random.randn(3,3,3)
print(arr)

[[[ 0.65950017  0.98202024  1.30280306]
  [ 0.71591924 -0.29462623  1.59158156]
  [-0.44241411 -0.1616594   0.22190266]]

 [[-0.24540441 -0.29174396 -1.64365114]
  [ 1.045773   -1.33732016  1.1393123 ]
  [-0.85759442 -0.60634144  0.9977411 ]]

 [[ 1.42451908  1.322817    0.56178447]
  [-0.85976143 -0.42177397 -0.3819595 ]
  [-0.46612982 -0.30627925  0.46191803]]]


In [130]:
#24 Replace array value with condition
arr[arr<0.5]=0
print(arr)

[[[0.65950017 0.98202024 1.30280306]
  [0.71591924 0.         1.59158156]
  [0.         0.         0.        ]]

 [[0.         0.         0.        ]
  [1.045773   0.         1.1393123 ]
  [0.         0.         0.9977411 ]]

 [[1.42451908 1.322817   0.56178447]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]]


In [137]:
#25
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
x+y

array([ 6,  8, 10, 12])

In [139]:
#26
x-y

array([-4, -4, -4, -4])

In [141]:
#27
x*y

array([ 5, 12, 21, 32])

In [143]:
#28
x/y

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [145]:
#29
a=np.array([1,2,3,4])
a*2

array([2, 4, 6, 8])

In [147]:
#30 Dot product
a=np.array([1,2])
b=np.array([2,1])
result=np.dot(a,b)
print(result)

4


In [149]:
#31 Adding scalar value to array which is called BROADCASTING
z=np.array([1,2,4])
z+1

array([2, 3, 5])

In [151]:
#32 finding mean 
a=np.array([1,2,3,4,5,6,7,8,9,10])
a.mean()

5.5

In [154]:
#33 Pi Use
print(np.pi)
a=np.array([0,np.pi/2,np.pi])
a

3.141592653589793


array([0.        , 1.57079633, 3.14159265])

In [157]:
#34 Sine function
a=np.array([0,30,45,60,90])
print('''Sine of the different angles''')
#Convert to radians by multiplying with pi/180
print(np.sin(a*np.pi/180))

Sine of the different angles
[0.         0.5        0.70710678 0.8660254  1.        ]


In [158]:
#35 Cos function
print('''Cosine of the different angles''')
#Convert to radians by multiplying with pi/180
print(np.cos(a*np.pi/180))

Cosine of the different angles
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [159]:
#36 Tan function
print('''Tangent of the different angles''')
#Convert to radians by multiplying with pi/180
print(np.tan(a*np.pi/180))

Tangent of the different angles
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [162]:
#37 Like function in this we copy the shape of the matrix
print(a)
np.zeros_like(a)

[ 0 30 45 60 90]


array([0, 0, 0, 0, 0])

In [164]:
#38 Using like function and multiplying its by one
b = np.ones_like(a) * 5 # + 5
b

array([5, 5, 5, 5, 5])

In [168]:
#39 Using full function
b=np.full((10,10),3)
b

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [171]:
#40 full with like
np.full_like(b,5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [178]:
#41 we are copying the data type, shape etc
print(a)
print(np.full_like(a,dtype=a.dtype,fill_value=2.5))

[ 0 30 45 60 90]
[2 2 2 2 2]


In [175]:
np.full_like(a, dtype=np.float64, fill_value=2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [181]:
#42 Empty like
np.empty_like(b)

array([[-1291074040,         328, -1291073208,         328, -1295437240,
                328, -1295437752,         328, -1293726520,         328],
       [-1293727672,         328, -1293727800,         328, -1293729080,
                328, -1298987384,         328, -1292827192,         328],
       [-1293726776,         328, -1292825016,         328, -1292824824,
                328, -1292824888,         328, -1292825848,         328],
       [-1293665784,         328, -1293668280,         328, -1293667768,
                328, -1293664824,         328, -1293668152,         328],
       [-1293666808,         328, -1293665208,         328, -1293667832,
                328, -1293665400,         328, -1293664760,         328],
       [-1293666872,         328, -1339382840,         328, -1297643448,
                328, -1293770808,         328, -1293772344,         328],
       [-1293773560,         328, -1293774008,         328, -1293772792,
                328, -1293771512,         328

In [189]:
#43 Nan function
np.full_like(a,2) * np.nan

array([nan, nan, nan, nan, nan])

In [190]:
#44 
np.full(a.shape, np.nan)

array([nan, nan, nan, nan, nan])

In [192]:
#45 eye function
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [194]:
#46 identity function
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [198]:
#47 checing in how many are devides fully by 2
print(a)
a % 2 ==0

[ 0 30 45 60 90]


array([ True,  True, False,  True,  True])

In [201]:
#48 Stacking in vertical shape
x=np.array([(1,2,3,4),(11,12,13,14)])
y=np.array([(5,6,7,8),(15,16,17,18)])

In [202]:
np.vstack((x,y))

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [ 5,  6,  7,  8],
       [15, 16, 17, 18]])

In [206]:
#49 Horizental stacking
np.hstack((x,y))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [11, 12, 13, 14, 15, 16, 17, 18]])

In [205]:
#50
x.ravel()

array([ 1,  2,  3,  4, 11, 12, 13, 14])